# Generated by Django 3.0.2 on 2020-03-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paresh', '0003_auto_20200318_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='delivery_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='invoice_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
