# Generated by Django 3.0.2 on 2020-03-18 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paresh', '0004_auto_20200318_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='delivery_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='billing',
            name='invoice_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='billing',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='products',
            name='words',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
