# Generated by Django 3.0.2 on 2020-03-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paresh', '0007_auto_20200319_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amount',
            name='gst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amount',
            name='sub_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amount',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
