# Generated by Django 3.0.2 on 2020-03-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paresh', '0011_auto_20200319_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='discount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='amount',
            name='gst',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='amount',
            name='sub_total',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='amount',
            name='total',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
