# Generated by Django 3.0.2 on 2020-03-19 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paresh', '0012_auto_20200319_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paresh.Billing'),
        ),
    ]
