# Generated by Django 3.0.2 on 2020-03-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paresh', '0013_auto_20200319_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='words',
            field=models.CharField(blank=True, default='Zero', max_length=100, null=True),
        ),
    ]
