# Generated by Django 3.0.2 on 2020-03-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caltesting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cal',
            name='a',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cal',
            name='b',
            field=models.IntegerField(null=True),
        ),
    ]
