# Generated by Django 3.0.2 on 2020-03-17 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caltesting', '0002_auto_20200317_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cal',
            name='num',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='caltesting.num'),
            preserve_default=False,
        ),
    ]
