# Generated by Django 3.0.2 on 2020-03-17 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caltesting', '0003_auto_20200317_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='cal',
            name='num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caltesting.invoi'),
        ),
        migrations.DeleteModel(
            name='num',
        ),
    ]
