# Generated by Django 3.0.2 on 2020-03-18 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caltesting', '0010_auto_20200318_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cal',
            name='num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caltesting.Invoi'),
        ),
    ]
