# Generated by Django 3.0.2 on 2020-03-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='buyer_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_name',
            field=models.TextField(),
        ),
    ]
